### ISSUE TITLE
`NATS: Subject must be supplied` when `msg.ack`

### ISSUE THREAD

**Issue by wojtkowiak** [nats-io/stan.js#115] opened 2019-06-18 13:28 UTC
I am getting this very weird situation in which sometimes I get `NATS: Subject must be supplied` when ack'ing a message. It goes away after restart. The weird part is that the connection is stable and I do receive messages on the subscription. But when this happens the instance cannot ack a message any longer, it always fail with this until I restart it.
Any idea what my be causing this?

**Comment by aricart** [comment] 2019-06-18 15:25
@wojtkowiak the error is coming from the underlying nats library. 

I think I partly understand the issue:

- Your client is sending out a subscription
- The server accepts it
- The subscription response is not returning to the client (`timeout` should be emitted)
- If timeout was emitted, the client cannot ack, so it needs to ignore any messages, and `close()` or `unsubscribe()`
The part that I am puzzled about is that you say the subscription was working normally. I wouldn't have expected the subscription to work.

Could you:

- Add a `timeout`, `error`, `ready` handlers to the subscription
- Add a `connection_lost` to the stan connection

**Comment by aricart** [comment] 2019-06-20 11:54
@wojkowiak any updates from your side?

**Comment by aricart** [comment] 2019-06-21 12:10
Can you please report the version of the server. @kozlovick can sub protocol messages be published by a different connection than subscription messages?

**Comment by wojtkowiak** [comment] 2019-06-24 06:50
@wojtkowiak sorry for stalling this, I am using `nats:1.4.0`, I will be adding some more logs and check out if I do listen to every events. Will get back on that.

> Your client is sending out a subscription
> The server accepts it
> The subscription response is not returning to the client (timeout should be emitted)
> If timeout was emitted, the client cannot ack, so it needs to ignore any messages from the subscription, and close() or unsubscribe()

From the logs I can see that subscription is opened correctly, I do receive messages, the processing usually takes no more than 2-5sec, ackTime is set to 20000. Then out of a sudden I get the error and like I said, I still do receive next messages.

**Comment by nazar-pc** [comment] 2019-07-15 09:30
I see the same issue in our setup.

NATS version: 1.4.1
NATS Streaming: 2.0.0
node-nats-streaming: 0.2.2

At some point some instances start getting this error and as was said before, there is no way to get rid of it until restart.

Also I looked as source code and it feels like there is nothing in JS library that may cause this.
Subject comes from protobuf and then used to publish acknowledgement.
Is there a chance this may be caused by NATS or NATS Streaming server?

**Comment by aricart** [comment] 2019-07-17 12:43
@nazar-pc the version for the nats-streaming-server doesn't seem to be correct. The currently released version is v0.15.1. Also it would be interesting to see if the `connection_lost` handler is getting called. Your application should restart if so. See https://github.com/nats-io/stan.js#connection-status

**Comment by nazar-pc** [comment] 2019-07-17 14:03
It says `version: 2.0.0` at `http://localhost:8222/varz`, but yes, turns out we have `:latest` image from Docker Hub currently running.

Yes, my application does have `connection_lost` callback and does graceful shutdown/restart when that happens. Apparently in this case it was not called for some reason.

This situation also correlates with increased load on our setup, so maybe there is actually something that should fire `connection_lost` or something like that.

**Comment by aricart** [comment] 2019-07-17 14:09
@nazar-pc the /varz endpoint is for the embedded nats-server. For nats-streaming you want to hit:
http://localhost:8222/streaming/<endpoint>
Where endpoint is:
- serverz
- storez
- clientsz
- channelsz

Wondering if you have a mix of streaming server versions? The libraries are backwards compatible, but if you have a mix of servers, it is possible that the connection_lost functionality is not available there.

**Comment by aricart** [comment] 2019-07-17 14:16
@nazar-pc Also you wouldn't by any chance be passing or accessing the NATS connection in the client directly. It would be awesome to print a stack trace on the error handler.

**Comment by nazar-pc** [comment] 2019-07-17 14:25
Hm... we've recently upgraded NATS Streaming, but not NATS itself. Only today we've tried to upgrade to NATS 2.0.2, but had issues and reverted back to 1.4.1. All instances are deployed using k8s operator, so they should all be exactly the same version in cluster.

In my case stack trace looks like this:
```
NatsError: Subject must be supplied
    at Client.publish (/code/node_modules/nats/lib/nats.js:1541:20)
    at Message.ack (/code/node_modules/node-nats-streaming/lib/stan.js:981:28)
    at QueueClient.<anonymous> (/code/dist/lib/QueueClient.js:99:21)
    at Generator.next (<anonymous>)
    at fulfilled (/code/dist/lib/QueueClient.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by nazar-pc** [comment] 2019-07-17 14:26
Or do you mean that NATS Streaming has something of v2.0.0 inside and may not play nicely with 1.4.1? I'm not familiar enough with NATS and didn't deploy it myself.

**Comment by aricart** [comment] 2019-07-17 14:32
My comment was regarding the connection_lost. Only 0.10.0 and newer versions of nats-streaming-server implement it.

**Comment by nazar-pc** [comment] 2019-09-03 15:21
Just happened again on a bunch on Node.js instances after load spike on NATS caused by departure of large k8s node (stop instance).
From now on will handle this as internal error and restart the whole app, but this needs to be tracked down to the root cause somehow and I have suspicion it is not in this library.

**Comment by aricart** [comment] 2019-09-03 16:57
@nazar-pc one question we have is whether the subscription is existing or is this a new subscription.

Is this a durable queue?

I think we are on to something, but we want more information before we say.

**Comment by aricart** [comment] 2019-09-03 16:57
@nazar-pc Also, are you setting the handler for the subscription before you get the `ready` notification from the subscription?

**Comment by aricart** [comment] 2019-09-03 16:59
@nazar-pc @kozlovic is seeing that the server might send you message before the protocol message comes back. So it seems that on the restart of the durable, is where the situation is happening.

**Comment by nazar-pc** [comment] 2019-09-03 18:01
> Is this a durable queue?

It is not, but it is using queue group with 2..4 nodes in it. In fact, we don't have durable queues at all.

> Also, are you setting the handler for the subscription before you get the ready notification from the subscription?

Yes, code looks like this:
```typescript
const subscriptionOptions = stan.subscriptionOptions()
    .setManualAckMode(true)
    .setMaxInFlight(200)
    .setStartWithLastReceived();
const subscription = this.stan.subscribe(
    'subject',
    'subject.queue-group-name',
    subscriptionOptions,
);
subscription.on('message', async (message: Message) => {
    try {
        // Work here
        message.ack();
    } catch (error) {
        // Handle unexpected error here
    }
});
```

Also we now use a moderately big non-cluster instance of NATS Streaming with embedded NATS.

**Comment by aricart** [comment] 2019-09-03 18:10
This should work - but the subscription has a 'ready' notification, you could hook up the 'message' handler, that would prevent the error from the NATS library, however, likely it will surface an 'error'/'timeout' on the subscription which would have been easier to diagnose.

**Comment by nazar-pc** [comment] 2019-09-03 18:19
Hm... we observe this on subscriptions that were active and running for days without issues, but suddenly we starte getting those errors that do not go away unless restarting.

**Comment by aricart** [comment] 2019-09-03 18:23
I think the stan client was completely re-initialized - so the subscriptions never saw any messages (there's no nulling of the value for the inbox). However there is something with the client on a queue group not getting the protocol response to the subscription before messages are handled, thus the error you are seeing.

**Comment by aricart** [comment] 2019-09-03 20:31
Here's an example for a subscription 'ready' handler:

```javascript
const STAN = require('node-nats-streaming');


const stan = STAN.connect('test-cluster', 'testid1234');
stan.on('connect', () => {
    const opts = stan.subscriptionOptions();
    opts.setManualAckMode(true);
    opts.setAckWait(1000);

    opts.setStartWithLastReceived();
    const sub = stan.subscribe('hello', opts);
    sub.on('ready', () => {
        sub.on('message', (msg) => {
            console.log(msg.getData());
        });
    });
    sub.on('error', (err) => {
        console.log('subscription failed', err);
    });
    sub.on('timeout', (err) => {
        console.log('subscription timeout', err)
    });
    sub.on('unsubscribed', () => {
        console.log('subscription unsubscribed')
    });
});
```

If the protocol message doesn't arrive within the default 2 second wait (this is shared with the connectTimeout, you'll see a timeout error. If a different error prevented the subscription, the error handler for the subscription will tell you that.

I understand this is contrived, and I think we are on to something where the server is sending a message before the protocol message, if that is the case and you have manual acks setup, you'll give a chance for the protocol message to arrive. The unack'ed message will be resent by the server. If you have automatic acks, then the expectation that messages should be received after the protocol message will hold, and the ack will fail with a missing subject. 

If you could instrument your service, perhaps we get an official confirmation that the client failed to process the subscription response, and messages were delivered to the client. I have a suspicion that this is what is happening. The client connects, creates the subscription, disconnects, subscription response is dropped, reconnects, but the client doesn't have an ack inbox to use. In this case, you'll be aware of the situation because the timeout handler above will catch it.

**Comment by nazar-pc** [comment] 2019-09-03 20:38
The issue is that this only happens under some unexpected load, not regularly. So while I can add that to the service, I can't promise that it will happen again within some reasonably amount of time.

What you're saying makes sense, but why are messages still coming in `.on('message', ...)` if subscription timed out already? Or is this where potential fix would be?

**Comment by aricart** [comment] 2019-09-03 21:05
Correct - the issue is that somehow the response from the server for the creation of the subscription has not yet been received by the client when the first message is arriving. This is why the ack fails with a missing subject. If the subscription was not new (had already processed messages), the subject would be there. 

I believe there's a reset (so the client is setting up new subscriptions when this happens). Or it could be that the client is disconnecting when the response to the protocol message is published, so the client doesn't see it. And on reconnect, the messages arrive, but because the setup process fails, the client will not have all the information it needs to ack. 

If you set your code as above it will be very clear that no handler is set until ready is called. If the response to the subscription is lost, you'll get a timeout. In either case you still have a problem, but at least we are closer to the reason.

**Comment by nazar-pc** [comment] 2019-09-03 21:09
Thanks for explanation, will try to add that to one of apps and will get back if/when I get any results.

I think it should be possible to reproduce this error somehow given NATS node little resources and then doing multi-client connections/disconnections under load or large spikes of incoming messages. At least in our case it only happens under significant load, even short-term.

**Comment by aricart** [comment] 2019-09-04 20:45
@kozlovic just merged a PR that could be the reason for this issue. The fix helps durable queue/or not subscriptions that are resumed.

https://github.com/nats-io/nats-streaming-server/pull/931

**Comment by kozlovic** [comment] 2019-09-04 20:51
@aricart Precision: the issue had to do with durables (queue or not) subscriptions. Since user is not using durables, it is unlikely.

**Comment by aricart** [comment] 2019-12-03 12:40
@nazar-pc looks like there has not been a resurgence of this issue. If you see it happening again, please reopen.

**Closed by aricart** 2019-12-03 12:40 UTC

**Comment by shanurrahman** [comment] 2020-05-15 09:42
hi,
So I am having a similar if not the same issue, the problem is if i try to subscribe to a subject before publishing the data for it, the subscription fails.

```(node:86554) UnhandledPromiseRejectionWarning: NatsError: Subject must be supplied
    at Client.publish (/Users/gamechange/Documents/gamechange/saleskey-project/realtime/node_modules/nats/lib/nats.js:1619:14)
    at Client.request (/Users/gamechange/Documents/gamechange/saleskey-project/realtime/node_modules/nats/lib/nats.js:1896:8)
    at Client.requestOne (/Users/gamechange/Documents/gamechange/saleskey-project/realtime/node_modules/nats/lib/nats.js:1983:15)
    at Stan.subscribe (/Users/gamechange/Documents/gamechange/saleskey-project/realtime/node_modules/node-nats-streaming/lib/stan.js:694:11)
    at Stream.<anonymous> (/Users/gamechange/Documents/gamechange/saleskey-project/realtime/src/stream.ts:54:38)
    at Generator.next (<anonymous>)
    at /Users/gamechange/Documents/gamechange/saleskey-project/realtime/src/stream.ts:15:71
    at new Promise (<anonymous>)```
