### ISSUE TITLE
Durable Group Subscriptions

### ISSUE THREAD

**Issue by KoryNunn** [nats-io/stan.js#118] opened 2019-06-27 23:39 UTC
Hi, I'm attempting to set up a durable group subscription where N subscribers in a group can consume a queue, and if all N consumers crash (no unsubscribing or closing) when any new subscriber connects, it will start processing any message not ACK'd by any subscriber in the group

As far as I can tell this is not possible, due durable subscriptions using a combination of the clientId and durable name, and since you can't have two consumers with the same client id, you can't have two subscribers sharing the same durable queue..?

Here is my test publisher:

```js
var stan = require('node-nats-streaming').connect('test-cluster', 'test-' + parseInt(Math.random() * 100000));

stan.on('connect', function () {
  setInterval(function(){
    stan.publish('foo', Date.now() + ' Hello node-nats-streaming!', function(err, guid){
      if(err) {
        return console.log('publish failed: ' + err);
      }
      console.log('published message with guid: ' + guid);
    });
  }, 1000)
});
```

And here is a test consumer that works with N subscribers, but does not get all messages:

```js
 var stan = require('node-nats-streaming').connect('test-cluster', 'test-' + parseInt(Math.random() * 100000));

stan.on('connect', function () {
  var opts = stan.subscriptionOptions();

  opts.setDeliverAllAvailable();
  opts.setDurableName('durable-name');

  var subscription = stan.subscribe('foo', 'group', opts);
  subscription.on('message', function (msg) {
    console.log('Received a message [' + msg.getSequence() + '] ' + msg.getData());
  });
});
```

Changing the clientId to a static value results in a test consumer that works with only ONE subscriber, but DOES consume every event in order even if it is killed and restarted while messages are being added to the queue.

Let me know if I'm not being clear, I'm happy to set up a working git repo if that helps.

Thanks.

**Comment by kozlovic** [comment] 2019-06-27 23:43
A durable subscription is unique for a given channel, client ID and durable name. The only way to have multiple subscriber sharing the load of a channel is through queue subscription. Those can be made durable too. 
Durable subscriptions do not have the client ID as part of the name, and that's simply because by definition a queue group will have multiple members, possibly from different connections/processes.
More information can be found [here](https://nats-io.github.io/docs/nats_streaming/channels/subscriptions/subscriptions.html) and specifically [here](https://nats-io.github.io/docs/nats_streaming/channels/subscriptions/queue-group.html#queue-group-in-nats-streaming)

**Comment by KoryNunn** [comment] 2019-06-28 00:16
Ok, so would you expect the above code to work as I intend then? Consumers seem to eventually get all messages, but they are wildly out of order, is this expected?

Example output:

```bash
.js 
Received a message [2067] 1561680933495 Hello node-nats-streaming!
Received a message [2066] 1561680932492 Hello node-nats-streaming!
Received a message [2068] 1561680934503 Hello node-nats-streaming!
Received a message [2069] 1561680935523 Hello node-nats-streaming!
Received a message [2070] 1561680936527 Hello node-nats-streaming!
Received a message [2071] 1561680937533 Hello node-nats-streaming!
Received a message [2072] 1561680938537 Hello node-nats-streaming!
Received a message [2073] 1561680939541 Hello node-nats-streaming!
^C
$ node consumeLatest.js 
Received a message [2074] 1561680940544 Hello node-nats-streaming!
^C
$ node consumeLatest.js 
Received a message [2077] 1561680943570 Hello node-nats-streaming!
Received a message [2076] 1561680942567 Hello node-nats-streaming!
Received a message [2078] 1561680944572 Hello node-nats-streaming!
Received a message [2075] 1561680941554 Hello node-nats-streaming!
Received a message [2081] 1561680947583 Hello node-nats-streaming!
Received a message [2080] 1561680946581 Hello node-nats-streaming!
Received a message [2083] 1561680949591 Hello node-nats-streaming!
Received a message [2084] 1561680950596 Hello node-nats-streaming!
Received a message [2079] 1561680945573 Hello node-nats-streaming!
...
```

**Comment by kozlovic** [comment] 2019-06-28 00:28
In your example where you use a durable queue sub and start N instances (each with different client ID), you should see that these subscribers of the same queue group consume messages from the channel. When dealing with a queue group, you cannot expect any ordering between members since each member may process message from a different thread or even process.
Server will deliver messages in the order they are in the channel, but redelivered messages may interleave with new messages.
When a member leaves the group, its unack'ed messages are reassigned to existing member(s).
The problem is that the streaming server does not know that the application has crashed until the number of pings to that client has reached the number of failed attempts (see -hbi, -hbt and -hbf in `nats-streaming-server -h`)

**Comment by KoryNunn** [comment] 2019-06-28 00:31
Ok thanks, (I actually found this: https://github.com/nats-io/stan.go/issues/179 which says effectively the same)

Would explicitly closing the connection (but not unsubscribing) improve this?

**Comment by kozlovic** [comment] 2019-06-28 00:39
Yes it would. But I just created an issue for the server where I noticed a possible issue (https://github.com/nats-io/nats-streaming-server/issues/862)

**Comment by aricart** [comment] 2019-07-08 15:06
@KoryNunn closing this issue, as it seems we have resolutions. Feel free to re-open/or open a new one if you have a more specific issue.

**Closed by aricart** 2019-07-08 15:06 UTC
